services:
  ctfd:
    build:
      context: ../..
      dockerfile: docker/ctfd/Dockerfile
    user: root
    restart: always
    environment:
      - UPLOAD_FOLDER=/var/uploads
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@db/ctfd
      - REDIS_URL=redis://cache:6379
      - WORKERS=1
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=-
      - ERROR_LOG=-
      - REVERSE_PROXY=true
    volumes:
      - ctfd_logs:/var/log/CTFd
      - ctfd_uploads:/var/uploads
    depends_on:
      - db
      - cache
    networks:
      default:
      internal:

  ctf-api:
    build: ../../ctf-api
    restart: always
    environment:
      - PROXMOX_SSH_TARGET=root@192.168.10.2
      - PROXMOX_SPAWN_SCRIPT=/root/spawn.sh
      - LAB_ALLOWED_ORIGINS=http://192.168.10.4,http://192.168.10.4:8000
    volumes:
      - /home/cce/.ssh:/root/.ssh:ro
    networks:
      default:

  nginx:
    image: nginx:stable
    restart: always
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - ctfd
      - ctf-api
    networks:
      default:

  db:
    image: mariadb:10.11
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=ctfd
      - MARIADB_USER=ctfd
      - MARIADB_PASSWORD=ctfd
      - MARIADB_DATABASE=ctfd
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      internal:
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: redis:4
    restart: always
    volumes:
      - redis_data:/data
    networks:
      internal:

networks:
  default:
  internal:
    internal: true

volumes:
  ctfd_logs:
  ctfd_uploads:
  db_data:
  redis_data:
